#gui/shape_data.py
#----------------------------------------------------------------------------------------------#
#Reference shape codes per coordination number (CN), following the SHAPE/Cosymlib nomenclature #
#----------------------------------------------------------------------------------------------#

SHAPE_REFERENCES = {
    2: {"L-2": "L-2", "vT-2": "vT-2", "vOC-2": "vOC-2"},
    3: {"TP-3": "TP-3", "vT-3": "vT-3", "fvOC-3": "fvOC-3", "mvOC-3": "mvOC-3"},
    4: {"SP-4": "SP-4", "T-4": "T-4", "SS-4": "SS-4", "vTBPY-4": "vTBPY-4"},
    5: {"PP-5": "PP-5", "vOC-5": "vOC-5", "TBPY-5": "TBPY-5", "SPY-5": "SPY-5", "JTBPY-5": "JTBPY-5"},
    6: {"HP-6": "HP-6", "PPY-6": "PPY-6", "OC-6": "OC-6", "TPR-6": "TPR-6", "JPPY-6": "JPPY-6"},
    7: {"HP-7": "HP-7", "HPY-7": "HPY-7", "PBPY-7": "PBPY-7", "COC-7": "COC-7", "CTPR-7": "CTPR-7", "JPBPY-7": "JPBPY-7", "JETPY-7": "JETPY-7"},
    8: {"OP-8": "OP-8", "HPY-8": "HPY-8", "HBPY-8": "HBPY-8", "CU-8": "CU-8", "SAPR-8": "SAPR-8", "TDD-8": "TDD-8", "JGBF-8": "JGBF-8", "JETBPY-8": "JETBPY-8", "JBTPR-8": "JBTPR-8", "BTPR-8": "BTPR-8", "JSD-8": "JSD-8", "TT-8": "TT-8", "ETBPY-8": "ETBPY-8"},
    9: {"EP-9": "EP-9", "OPY-9": "OPY-9", "HBPY-9": "HBPY-9", "JTC-9": "JTC-9", "JCCU-9": "JCCU-9", "CCU-9": "CCU-9", "JCSAPR-9": "JCSAPR-9", "CSAPR-9": "CSAPR-9", "JTCTPR-9": "JTCTPR-9", "TCTPR-9": "TCTPR-9", "JTDIC-9": "JTDIC-9", "HH-9": "HH-9", "MFF-9": "MFF-9"},
    10: {"DP-10": "DP-10", "EPY-10": "EPY-10", "OBPY-10": "OBPY-10", "PPR-10": "PPR-10", "PAPR-10": "PAPR-10", "JBCCU-10": "JBCCU-10", "JBCSAPR-10": "JBCSAPR-10", "JMBIC-10": "JMBIC-10", "JATDI-10": "JATDI-10", "JSPC-10": "JSPC-10", "SDD-10": "SDD-10", "TD-10": "TD-10", "HD-10": "HD-10"},
    11: {"HP-11": "HP-11", "DPY-11": "DPY-11", "EBPY-11": "EBPY-11", "JCPPR-11": "JCPPR-11", "JCPAPR-11": "JCPAPR-11", "JAPPR-11": "JAPPR-11", "JASPC-11": "JASPC-11"},
    12: {"DP-12": "DP-12", "HPY-12": "HPY-12", "DBPY-12": "DBPY-12", "HPR-12": "HPR-12", "HAPR-12": "HAPR-12", "TT-12": "TT-12", "COC-12": "COC-12", "ACOC-12": "ACOC-12", "IC-12": "IC-12", "JSC-12": "JSC-12", "JEPBPY-12": "JEPBPY-12", "JBAPPR-12": "JBAPPR-12", "JSPMC-12": "JSPMC-12"}
}

SHAPE_FULL_NAMES = {
    "L-2": "Linear",
    "vT-2": "Divacant tetrahedron",
    "vOC-2": "Tetravacant octahedron",
    "TP-3": "Trigonal Planar",
    "vT-3": "Pyramid",
    "fvOC-3": "Fac-Trivacant Octahedron",
    "mvOC-3": "Mer-Trivacant Octahedron",
    "SP-4": "Square Planar",
    "T-4": "Tetrahedron",
    "SS-4": "Seesaw",
    "vTBPY-4": "Axially vacant trigonal bipyramid",
    "PP-5": "Pentagon",
    "vOC-5": "Vacant Octahedron",
    "TBPY-5": "Trigonal Bipyramid",
    "SPY-5": "Square Pyramid",
    "JTBPY-5": "Johnson trigonal Bipyramid",
    "HP-6": "Hexagon",
    "PPY-6": "Pentagonal Pyramid",
    "OC-6": "Octahedron",
    "TPR-6": "Trigonal Prism",
    "JPPY-6": "Johnson Pentagonal Pyramid",
    "HP-7": "Heptagon",
    "HPY-7": "Hexagonal Pyramid",
    "PBPY-7": "Pentagonal Bipyramid",
    "COC-7": "Capped Octahedron",
    "CTPR-7": "Capped Trigonal Prism",
    "JPBPY-7": "Johnson Pentagonal Bipyramid",
    "JETPY-7": "Elongated triangular pyramid",
    "OP-8": "Octagon",
    "HPY-8": "Heptagonal pyramid",
    "HBPY-8": "Hexagonal bipyramid",
    "CU-8": "Cube",
    "SAPR-8": "Square Antiprism",
    "TDD-8": "Triangular Dodecahedron",
    "JGBF-8": "Johnson - Gyrobifastigium",
    "JETBPY-8": "Johnson - Elongated Triangular bipyramid",
    "JBTPR-8": "Johnson - Biaugmented trigonal prism",
    "BTPR-8": "Biaugmented trigonal prism",
    "JSD-8": "Snub disphenoid",
    "TT-8": "Triakis tetrahedron",
    "ETBPY-8": "Elongated trigonal bipyramid",
    "EP-9": "Enneagon",
    "OPY-9": "Octagonal pyramid",
    "HBPY-9": "Heptagonal bipyramid",
    "JTC-9": "Triangular cupola",
    "JCCU-9": "Capped cube (Elongated square pyramid)",
    "CCU-9": "Capped Cube",
    "JCSAPR-9": "Capped sq. antiprism (Gyroelongated square pyramid)",
    "CSAPR-9": "Capped Square Antiprism",
    "JTCTPR-9": "Tricapped trigonal prism (J51)",
    "TCTPR-9": "Tricapped trigonal prism",
    "JTDIC-9": "Tridiminished icosahedron",
    "HH-9": "Hula-hoop",
    "MFF-9": "Muffin",
    "DP-10": "Decagon",
    "EPY-10": "Enneagonal pyramid",
    "OBPY-10": "Octagonal bipyramid",
    "PPR-10": "Pentagonal prism",
    "PAPR-10": "Pentagonal Antiprism",
    "JBCCU-10": "Bicapped cube (Elongated square bipyramid)",
    "JBCSAPR-10": "Bicapped square antiprism (Gyroelongated square bipyramid)",
    "JMBIC-10": "Metabidiminished icosahedron",
    "JATDI-10": "Augmented tridiminished icosahedron",
    "JSPC-10": "Sphenocorona",
    "SDD-10": "Staggered dodecahedron",
    "TD-10": "Tetradecahedron",
    "HD-10": "Hexadecahedron",
    "HP-11": "Hendecagon",
    "DPY-11": "Decagonal pyramid",
    "EBPY-11": "Enneagonal bipyramid",
    "JCPPR-11": "JCapped pent. Prism (Elongated pentagonal pyramid)",
    "JCPAPR-11": "Capped pent. antiprism (Gyroelongated pentagonal pyramid)",
    "JAPPR-11": "Augmented pentagonal prism",
    "JASPC-11": "Augmented sphenocorona",
    "DP-12": "Dodecagon",
    "HPY-12": "Hendecagonal pyramid",
    "DBPY-12": "Dodecagonal Bipyramid",
    "HPR-12": "Hexagonal prism",
    "HAPR-12": "Hexagonal Antiprism",
    "TT-12": "Truncated tetrahedron",
    "COC-12": "Cuboctahedron",
    "ACOC-12": "Anticuboctahedron ",
    "IC-12": "Icosahedron",
    "JSC-12": "Square cupola",
    "JEPBPY-12": "Elongated pentagonal bipyramid",
    "JBAPPR-12": "Biaugmented pentagonal prism",
    "JSPMC-12": "Sphenomegacorona"
}